name: CI -> Deploy to My website
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Here is the deployment action
      - name: Upload from dist via FTP
        uses: adilson/ftp-deployment-action@latest
        with:
          server: adilsonxdesouza.somee.com/www.adilsonxdesouza.somee.com
          user: adilsonxavier
          password: Maysaaxs2004*
          local_dir: "./dist"
          # remote_dir: public_html/
          delete: "true"